table customers
	lineageTag: 53351558-b45e-437c-9584-0599f6fc988d

	measure Customer_avg_age = AVERAGE(customers[customer_age])
		lineageTag: b13b01bc-d173-47f2-982f-89f8204c6115

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column customer_id
		dataType: int64
		formatString: 0
		lineageTag: 3401d653-e83d-4669-988b-5de4540fa01b
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column customer_name
		dataType: string
		lineageTag: 35118bbb-85e5-45a2-ade2-629fb0d1e268
		summarizeBy: none
		sourceColumn: customer_name

		annotation SummarizationSetBy = Automatic

	column customer_payment_type
		dataType: string
		lineageTag: 0d4bea56-f446-449d-93af-92a65442b751
		summarizeBy: none
		sourceColumn: customer_payment_type

		annotation SummarizationSetBy = Automatic

	column customer_age
		dataType: int64
		formatString: 0
		lineageTag: eeb29ba5-8f9b-4fe6-8980-a49bf516099e
		summarizeBy: sum
		sourceColumn: customer_age

		annotation SummarizationSetBy = Automatic

	column customer_region
		dataType: string
		lineageTag: 00858b9b-7a9e-4595-a12c-66777010eb27
		summarizeBy: none
		sourceColumn: customer_region

		annotation SummarizationSetBy = Automatic

	column customer_signup_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: b6145c97-bfd4-42a0-953d-918b8355d98c
		summarizeBy: none
		sourceColumn: customer_signup_date

		variation Variation
			isDefault
			relationship: f460a8f5-5070-430c-95e2-db8793642767
			defaultHierarchy: LocalDateTable_3806a01e-cd33-465f-a9e9-5c2ecf3e82aa.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition customers = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\Adebayo Olumide\Desktop\My-DataAnalyst-Portfolio\PowerBI\Projects\data-viz-project\customers.csv"), [Delimiter = ",", Columns = 6, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"customer_id", Int64.Type}, {"customer_name", type text}, {"customer_payment_type", type text}, {"customer_age", Int64.Type}, {"customer_region", type text}, {"customer_signup_date", type date}})
				in
				  #"Changed column type"

	annotation PBI_ResultType = Table

