table products
	lineageTag: 8475c643-6423-490a-85ee-5f6f59f1eb51

	column product_id
		dataType: int64
		formatString: 0
		lineageTag: ab6b44fd-440f-4106-838d-4e7cff801630
		summarizeBy: none
		sourceColumn: product_id

		annotation SummarizationSetBy = Automatic

	column product_name
		dataType: string
		lineageTag: 55de734a-e3a4-4d27-8260-1b0664e8d1bc
		summarizeBy: none
		sourceColumn: product_name

		annotation SummarizationSetBy = Automatic

	column product_category
		dataType: string
		lineageTag: 18171fee-6b76-4d51-b5af-2c0e7a27249e
		summarizeBy: none
		sourceColumn: product_category

		annotation SummarizationSetBy = Automatic

	column product_brand
		dataType: string
		lineageTag: 5b882bed-9bfc-428a-a9f4-87ec1c18afe7
		summarizeBy: none
		sourceColumn: product_brand

		annotation SummarizationSetBy = Automatic

	column product_model
		dataType: string
		lineageTag: 6853abd0-91cb-46a7-baf2-235035e28c06
		summarizeBy: none
		sourceColumn: product_model

		annotation SummarizationSetBy = Automatic

	column product_list_price
		dataType: double
		lineageTag: 3ddadf52-2944-4c2c-9ff4-a73879693203
		summarizeBy: none
		sourceColumn: product_list_price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_standard_cost
		dataType: double
		lineageTag: 63af460a-0c00-48e3-b775-d73d0b8b60bf
		summarizeBy: none
		sourceColumn: product_standard_cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column product_is_active
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 32c55bb6-e7a7-4644-9a6e-4f6613140c10
		summarizeBy: none
		sourceColumn: product_is_active

		annotation SummarizationSetBy = Automatic

	partition products = m
		mode: import
		source =
				let
				  Source = Csv.Document(File.Contents("C:\Users\Adebayo Olumide\Desktop\My-DataAnalyst-Portfolio\PowerBI\Projects\data-viz-project\products.csv"), [Delimiter = ",", Columns = 8, QuoteStyle = QuoteStyle.None]),
				  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"product_id", Int64.Type}, {"product_name", type text}, {"product_category", type text}, {"product_brand", type text}, {"product_model", type text}, {"product_list_price", type number}, {"product_standard_cost", type number}, {"product_is_active", type logical}})
				in
				  #"Changed column type"

